### ISSUE TITLE
ASAN: SEGV on unknown address

### ISSUE THREAD

**Issue by Manishearth** [servo/rust-url#283]
found by cargo-fuzz

```rust
extern crate url;
use url::Url;
fn main() {
    let spec = [0x0,0x77,0x73,0x73,0x3a,0xd8,0xbe,0x0,0x0,0xd9,0xa3];
    let spec = ::std::str::from_utf8(&spec).unwrap();
    let mut url = Url::parse(spec).ok();
    println!("{:?}", url);
}
```

Build rust-url (on x86-64 linux) with `RUSTFLAGS=-Cpasses=sancov -Cllvm-args=-sanitizer-coverage-level=3 -Zsanitizer=address -Cpanic=abort`, and then compile this with `rustc test.rs -L fuzz/target/debug/ -L fuzz/target/debug/deps/ -Cpanic=abort -Zsanitizer=address`, and then run with `ASAN_OPTIONS=detect_odr_violation=0`. You will get:

```
manishearth@cyclotron:~/mozilla/fuzz/rust-url$ ASAN_OPTIONS=detect_odr_violation=0 ./test
ASAN:DEADLYSIGNAL
=================================================================
==16900==ERROR: AddressSanitizer: SEGV on unknown address 0x10009aea3eae (pc 0x56520bfb6290 bp 0x7fffd755f7d0 sp 0x
7fffd755f460 T0)
==16900==The signal is caused by a READ memory access.
    #0 0x56520bfb628f  (/home/manishearth/mozilla/fuzz/rust-url/test+0x1d828f)
    #1 0x56520bfdcb13  (/home/manishearth/mozilla/fuzz/rust-url/test+0x1feb13)
    #2 0x56520bfe1875  (/home/manishearth/mozilla/fuzz/rust-url/test+0x203875)
    #3 0x56520c011dd0  (/home/manishearth/mozilla/fuzz/rust-url/test+0x233dd0)
    #4 0x56520c01144e  (/home/manishearth/mozilla/fuzz/rust-url/test+0x23344e)
    #5 0x56520c01a30c  (/home/manishearth/mozilla/fuzz/rust-url/test+0x23c30c)
    #6 0x56520c01b8fa  (/home/manishearth/mozilla/fuzz/rust-url/test+0x23d8fa)
    #7 0x56520bf48619  (/home/manishearth/mozilla/fuzz/rust-url/test+0x16a619)
    #8 0x56520bf788a8  (/home/manishearth/mozilla/fuzz/rust-url/test+0x19a8a8)
    #9 0x56520bf751a1  (/home/manishearth/mozilla/fuzz/rust-url/test+0x1971a1)
    #10 0x56520bf712e8  (/home/manishearth/mozilla/fuzz/rust-url/test+0x1932e8)
    #11 0x56520bf60317  (/home/manishearth/mozilla/fuzz/rust-url/test+0x182317)
    #12 0x56520bf5dae7  (/home/manishearth/mozilla/fuzz/rust-url/test+0x17fae7)
    #13 0x56520bf9952b  (/home/manishearth/mozilla/fuzz/rust-url/test+0x1bb52b)
    #14 0x56520bec96a0  (/home/manishearth/mozilla/fuzz/rust-url/test+0xeb6a0)
    #15 0x56520beccc66  (/home/manishearth/mozilla/fuzz/rust-url/test+0xeec66)
    #16 0x56520c05b07b  (/home/manishearth/mozilla/fuzz/rust-url/test+0x27d07b)
```

Can't repro outside of ASAN, I presume the segfault is within a cache line or something.

**Comment by Manishearth** [comment]
cc @SimonSapin 

@nagisa Any tips on how to debug this?

**Comment by Manishearth** [comment]
Ah, I can get a backtrace from gdb.

```
#0  0x000055555572c290 in core::option::{{impl}}::map<u32,((), u32),closure> (self=..., f=...)
    at /checkout/src/libcore/option.rs:383
#1  0x0000555555752b14 in core::iter::iterator::select_fold1<core::iter::Filter<core::iter::Map<core::slice::Iter<c
har>, closure>, closure>,(),closure,closure> (it=..., f_proj=..., f_cmp=...)
    at /checkout/src/libcore/iter/iterator.rs:2180
#2  0x0000555555757876 in core::iter::iterator::Iterator::min<core::iter::Filter<core::iter::Map<core::slice::Iter<
char>, closure>, closure>> (self=...) at /checkout/src/libcore/iter/iterator.rs:1668
#3  0x0000555555787dd1 in idna::punycode::encode (input=...)
    at /home/manishearth/mozilla/fuzz/rust-url/idna/src/punycode.rs:160
#4  0x000055555578744f in idna::punycode::encode_str (input=...)
    at /home/manishearth/mozilla/fuzz/rust-url/idna/src/punycode.rs:134
#5  0x000055555579030d in idna::uts46::to_ascii (domain=..., flags=...)
    at /home/manishearth/mozilla/fuzz/rust-url/idna/src/uts46.rs:283
#6  0x00005555557918fb in idna::domain_to_ascii (domain=...)
    at /home/manishearth/mozilla/fuzz/rust-url/idna/src/lib.rs:50
#7  0x00005555556be61a in url::host::{{impl}}::parse (input=...)
    at /home/manishearth/mozilla/fuzz/rust-url/src/host.rs:149
#8  0x00005555556ee8a9 in url::parser::{{impl}}::parse_host (input=..., scheme_type=SpecialNotFile)
    at /home/manishearth/mozilla/fuzz/rust-url/src/parser.rs:784
#9  0x00005555556eb1a2 in url::parser::{{impl}}::parse_host_and_port (self=0x7fffffffb960, input=...,
    scheme_end=3, scheme_type=SpecialNotFile) at /home/manishearth/mozilla/fuzz/rust-url/src/parser.rs:724
#10 0x00005555556e72e9 in url::parser::{{impl}}::after_double_slash (self=..., input=...,
    scheme_type=SpecialNotFile, scheme_end=3) at /home/manishearth/mozilla/fuzz/rust-url/src/parser.rs:661
#11 0x00005555556d6318 in url::parser::{{impl}}::parse_with_scheme (self=..., input=...)
    at /home/manishearth/mozilla/fuzz/rust-url/src/parser.rs:339
#12 0x00005555556d3ae8 in url::parser::{{impl}}::parse_url (self=..., input=...)
    at /home/manishearth/mozilla/fuzz/rust-url/src/parser.rs:261
#13 0x000055555570f52c in url::{{impl}}::parse (self=..., input=...)
...
```

**Comment by Manishearth** [comment]
Perhaps we messed up on the bounds of the unicodeifying? Providing a length longer than the actual string would probably not segfault.

**Comment by Manishearth** [comment]
On rebuilding I can't repro, might be that this wasn't compiled with sanitizer support in all deps.

**Comment by nagisa** [comment]
This is the same thing I was getting on the JPEG decoder.

**Comment by Manishearth** [comment]
probably an ASAN bug.
