### ISSUE TITLE
FAILED: test "https://faß.ExAmPlE/" @ base "about:blank"

### ISSUE THREAD

**Issue by cuviper** [servo/rust-url#437]
I'm seeing this failure when I test the published url-1.7.0:

```
test "https://faß.ExAmPlE/" @ base "about:blank" ... thread '"https://faß.ExAmPlE/" @ base "about:blank"' panicked at '"https://fass.example/" != expected.href "https://xn--fa-hia.example/" for URL "https://fass.example/"', tests/data.rs:65:4
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: std::panicking::begin_panic_fmt
   7: data::run_parsing
             at tests/data.rs:65
   8: data::collect_parsing::{{closure}}
             at tests/data.rs:139
   9: test::TestFn::dyn_test_fn::{{closure}}
             at /home/jistone/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-test-0.2.0/src/lib.rs:164
  10: test::run_test::run_test_inner::{{closure}}::{{closure}}
             at /home/jistone/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-test-0.2.0/src/lib.rs:1168
FAILED
```

However, this test passes when I run from the git repo.  Perhaps one of the workspace crates needs to publish a new version?

**Comment by ignatenkobrain** [comment]
ping?

**Comment by SimonSapin** [comment]
Just published https://crates.io/crates/idna/0.1.5, which I believe fixes this.
